### ISSUE TITLE
Docker Init Script

### ISSUE THREAD

**Issue by pet1330** [pet1330/pgr_system#28]
I thought it might be worth documenting the steps taken to get the docker image running. Below is a list of steps that I have taken, but as you mentioned earlier, we should probably put this into an init script:

Install `docker-compose`

Create the necessary host files to act as persistent storage:
```
mkdir -p /srv/pgr/storage/logs
mkdir -p /srv/pgr/storage/debugbar
mkdir -p /srv/pgr/storage/framework/cache
mkdir -p /srv/pgr/storage/framework/testing
mkdir -p /srv/pgr/storage/framework/views
mkdir -p /srv/pgr/storage/framework/sessions
chown -R www-data:www-data /srv/pgr/storage
```

Clone this repository into your local workspace and copy the `.env` file:
```
git clone https://github.com/pet1330/pgr_system
cp pgr_system/.env.example /srv/pgr/config/.env
```
update the `.env` with your favioute editor of choice

```
vim /srv/pgr/config/.env
```

then, run `docker-compose up`
```
docker-compose up
```

In a separate terminal, run 
```
docker-compose exec db bash
mysql -uroot
create database [DATABASE_NAME];
quit
```
then Ctrl-C out of the container

then run 
```
docker-compose exec pgr bash
```
Here you will need to migrate the database by running

```
php artisan migrate
```

**Comment by marc-hanheide** [comment]
Moved to a script to initialise the host dirs
