### ISSUE TITLE
Remove email change from Student creation form

### ISSUE THREAD

**Issue by pet1330** [pet1330/pgr_system#6]
SAML uses the email address as the unique identifier, but students are currently found using their student ID. This could cause issues if the email address is entered incorrectly.

**Comment by marc-hanheide** [comment]
Is this still an issue? IDs are entered on creation of users, not email.

**Comment by pet1330** [comment]
Yeah, the SSO finds a user using the email address provided, not the user's university ID. This means if the email address is wrong, then the user has to be manually deleted which is not possible from the web interface.

**Comment by marc-hanheide** [comment]
Got it, ok, but it's not urgent I'd say
